-- ── Fix: worker swarm / "floating photo count" ────────────────────────────
-- Root cause of the bug where one product was generated by several workers at
-- once (count jumped up then down, same images regenerated, credit burned):
--   1. claim_generation marked a job "stale" and re-claimable after only 25s,
--      but a single worker pass runs up to 45-60s → a still-running job was
--      handed to a second worker → both overwrote the same arrays.
--   2. No cap on how many jobs run at once → all N products processed in
--      parallel → Vertex 429s + thrash.
--
-- Fix: (a) stale window 90s (> one pass, so a live worker is never displaced);
--      (b) a hard concurrency cap (p_max_lanes) on actively-processing jobs;
--      (c) an advisory lock so the count+claim is serialized → the cap is exact
--          even when many workers wake at the same instant.

DROP FUNCTION IF EXISTS claim_generation(int);

CREATE OR REPLACE FUNCTION claim_generation(
  p_stale_seconds int DEFAULT 90,
  p_max_lanes     int DEFAULT 2
)
RETURNS SETOF generations
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  gid    uuid;
  active int;
BEGIN
  -- Serialize all claims so the lane count is consistent (held until commit).
  PERFORM pg_advisory_xact_lock(hashtext('photoforge_claim_generation'));

  -- How many jobs are actively being worked right now (claim still fresh)?
  SELECT count(*) INTO active
    FROM generations
   WHERE status = 'processing'
     AND claimed_at IS NOT NULL
     AND claimed_at > now() - make_interval(secs => p_stale_seconds);

  IF active >= p_max_lanes THEN
    RETURN;                         -- at capacity → take nothing
  END IF;

  SELECT id INTO gid
    FROM generations
   WHERE status = 'queued'
      OR (status = 'processing'
          AND (claimed_at IS NULL OR claimed_at < now() - make_interval(secs => p_stale_seconds)))
   ORDER BY created_at
   FOR UPDATE SKIP LOCKED
   LIMIT 1;

  IF gid IS NULL THEN RETURN; END IF;

  UPDATE generations SET status = 'processing', claimed_at = now() WHERE id = gid;
  RETURN QUERY SELECT * FROM generations WHERE id = gid;
END $$;

REVOKE ALL ON FUNCTION claim_generation(int, int) FROM public, anon, authenticated;
